version: 0.1.{build}

init:
    - git config --global core.autocrlf input

shallow_clone: false
skip_branch_with_pr: true

matrix:
    fast_finish: true

platform:
    - x64

configuration:
    - Release

environment:
    matrix:
        - job_name: Windows build
          appveyor_build_worker_image: Visual Studio 2017

for:
    -
        matrix:
          only:
            - job_name: Windows build
        clone_folder: c:\projects\yaml-parser
        before_build:
            - git submodule update --init --recursive
        build_script:
            - mkdir build
            - cd build
            - cmake -G "Visual Studio 15 2017 Win64" -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=ON ..
            - cmake --build . --config Release
        test_script:
            - C:\projects\yaml-parser\build\tests\Release\yaml-parser-tests.exe --gtest_output=xml || cd .
        after_test:
            - curl -F 'file=C:\projects\yaml-arser\build\tests\Release\test_detail.xml' "https://ci.appveyor.com/api/testresults/junit/%APPVEYOR_JOB_ID%"
        artifacts:
            - path: build\*\yaml-parser.dll
            - path: build\**\test_detail.xml

install:

deploy:
    - provider: GitHub
      auth_token:
        secure: XDu4+kIKFFYWIc3yR7x9eX1kWZzF5aBmItTxzytX+Rwy5bwazcAHuN+wzOe8XkOE
      draft: false
      prerelease: false
      on:
        branch: master
        APPVEYOR_REPO_TAG: true

